apiVersion: v1
kind: Service
metadata:
  name: orderdetail-service
  labels:
    name: orderdetail
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 80
  selector:
    app: orderdetail-pod
